CREATE TABLE IF NOT EXISTS rooms (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, node_id TEXT NOT NULL, fencing_token BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS recording_jobs (id TEXT PRIMARY KEY, room_id TEXT NOT NULL, status TEXT NOT NULL, started_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, error TEXT);
CREATE TABLE IF NOT EXISTS node_leases (room_id TEXT PRIMARY KEY, owner TEXT NOT NULL, fencing_token BIGINT NOT NULL, expires_at TIMESTAMPTZ NOT NULL);
